### ISSUE TITLE
Upgrade to latest project keeper

### ISSUE THREAD

**Issue by kaklakariada** [exasol/tableau-connector#76]
This project uses an old version of PK and has many exclusions:

```yml
  - "E-PK-CORE-18: Outdated content: '.github/workflows/ci-build.yml'"
  - "E-PK-CORE-18: Outdated content: '.github/workflows/release_droid_upload_github_release_assets.yml'"
  - "E-PK-CORE-17: Missing required file: '.github/workflows/ci-build-next-java.yml'"
  - "E-PK-CORE-17: Missing required file: '.github/workflows/dependencies_check.yml'"
  - "E-PK-CORE-17: Missing required file: '.github/workflows/release_droid_prepare_original_checksum.yml'"
  - "E-PK-CORE-17: Missing required file: '.github/workflows/release_droid_print_quick_checksum.yml'"
```

```[tasklist]
### Tasks
- [ ] Upgrade PK
- [ ] Remove exclusion for ci-build.yml and adapt workflow steps
- [ ] Adapt workflow steps for release build
- [ ] Add dependency check workflows
```

**Comment by kaklakariada** [comment]
Already implemented with a previous PR
